### ISSUE TITLE
2.1 tag missing prefix "v"

### ISSUE THREAD

**Issue by bureddy** [NVIDIA/gdrcopy#154] opened 2020-12-02 20:18 UTC
not a priority issue. but it will be good to have a consistent pattern.  our sysadmin had to spend some time to figure it out why scripts are not working 

```
git tag -l
2.1
v1.3
v2.0
v2.0-beta.2
v2.0-beta.3
v2.0-beta.4
v2.1-beta1
v2.1-beta2
```

**Comment by traveller42** [comment] 2020-12-09 21:50
The link in the Changelog file uses v2.1, so it currently 404s.

**Comment by drossetti** [comment] 2020-12-11 02:24
@bureddy thanks for reporting the issue
@pakmarkthub please have a look

**Comment by pakmarkthub** [comment] 2020-12-11 05:37
Thank you @bureddy and @traveller42 for reporting this issue. I have fixed it. Now it should looks like this.

```
$ git tag -l
v1.3
v2.0
v2.0-beta.1
v2.0-beta.2
v2.0-beta.3
v2.0-beta.4
v2.1
v2.1-beta1
v2.1-beta2
```

Also the link in the Changelog file should work now. Can you confirm?

**Comment by traveller42** [comment] 2020-12-11 14:57
I can confirm that the link is working.

**Comment by pakmarkthub** [comment] 2021-01-04 07:31
Fixed. Closing.

**Closed by pakmarkthub** 2021-01-04 07:31 UTC
Labels: enhancement
