### ISSUE TITLE
io_remap_pfn_range() failure caused gdr_map() to return EAGAIN

### ISSUE THREAD

**Issue by wzamazon** [NVIDIA/gdrcopy#240] opened 2022-12-08 21:08 UTC
Hi, when using gdrcopy. Sometimes `gdr_map`  will failed with return code of -EAGAIN (-11).

In the dmesg, I can see error like

```
[1655746.266887] gdrdrv:gdrdrv_remap_gpu_mem:error in gdrdrv_io_remap_pfn_range()
[1655746.272760] gdrdrv:gdrdrv_mmap:error -11 in gdrdrv_remap_gpu_mem
```

Can you help understand what caused these errors and how can I fix them?

**Comment by drossetti** [comment] 2022-12-09 00:55
@pakmarkthub FYI
@wzamazon thanks for reporting this problem.
We need a bit more background, at least:
- kernel version
- Host platform, e.g. CPU
- GPU: type, GPU driver release version
- workload: multithreaded vs single-threaded vs multi-process, how many GPUs per process

**Comment by wzamazon** [comment] 2022-12-09 01:03
Thank you for your reply!

I was using Amazon Linux 2 on an AWS p4d instance.

kernel version:  5.10.135-122.509.amzn2.x86_64
Host platform: Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
GPU: NVIDIA A100
NVIDIA Driver version: 470.141.03
CUDA version: 11.4
workload is: cuda aware gromacs. The application is multi-threaded, with 1 GPU per process.

**Comment by wzamazon** [comment] 2022-12-09 01:12
I did some debugging and found that  when `io_remap_pfn_range()` failed, it return code is EINVAL (22).

**Comment by drossetti** [comment] 2022-12-09 01:14
do you have IS_ENABLED(CONFIG_ARCH_HAS_CC_PLATFORM) set in your kernel config?

**Comment by wzamazon** [comment] 2022-12-09 01:15
> do you have IS_ENABLED(CONFIG_ARCH_HAS_CC_PLATFORM) set in your kernel config?

I do not know. How can I check that?

**Comment by drossetti** [comment] 2022-12-09 01:18
on a recent kernel:
grep ARCH_HAS /boot/config-$(uname -r)|grep PLA
CONFIG_ARCH_HAS_CC_PLATFORM=y

**Comment by drossetti** [comment] 2022-12-09 01:32
What if your retry the call when gdr_map() returns EAGAIN?

**Comment by pakmarkthub** [comment] 2022-12-09 01:33
Hi @wzamazon,
A few questions:
- Are you using GDRCopy v2.3 or from the master branch?
- Have you seen this issue with other applications, especially with `copybw` and `sanity` that come with GDRCopy?
- Is it easily reproducible? Do you have a simple application to reproduce this issue so that we can study?

**Comment by wzamazon** [comment] 2022-12-09 15:58
@drossetti 

I have

>do you have IS_ENABLED(CONFIG_ARCH_HAS_CC_PLATFORM) set in your kernel config?

CONFIG_ARCH_HAS_CC_PLATFORM=y

> What if you retry the call when gdr_map() returns EAGAIN?

Thanks!  I will try

@pakmarkthub 

> Are you using GDRCopy v2.3 or from the master branch?

I tried both

> Have you seen this issue with other applications, especially with copybw and sanity that come with GDRCopy?

copybw and sanity works fine.

> Is it easily reproducible? Do you have a simple application (simpler than gromacs) to reproduce this issue so that we can study?

It happens consistently with gromacs. I will try to create a simpler reproducer.

**Comment by wzamazon** [comment] 2022-12-09 16:27
>What if you retry the call when gdr_map() returns EAGAIN?

Just added retry if `gdr_map()` returnes EAGIN, and it leads to an infinite loop.

**Comment by drossetti** [comment] 2022-12-09 21:22
There might be a bug related to CC on Intel. This is by code inspection, so I might be wrong.

Our code has:
#if (defined(CONFIG_X86_64) || defined(CONFIG_X86_32)) && IS_ENABLED(CONFIG_ARCH_HAS_CC_PLATFORM)
    return remap_pfn_range(vma, vaddr, pfn, size, __pgprot(__sme_clr(pgprot_val(prot))));
where __pgprot(__sme_clr(pgprot_val(prot)) is coming from the expansion of pgprot_decrypted as it was in 5.10.135. 

That code has been changed, probably to accomodate for a difference between AMD and Intel CC, see for example https://elixir.bootlin.com/linux/v5.19.17/source/arch/x86/coco/core.c#L106:
	/*
	 * Both AMD and Intel use a bit in the page table to indicate
	 * encryption status of the page.
	 *
	 * - for AMD, bit *set* means the page is encrypted
	 * - for Intel *clear* means encrypted.
	 */

@wzamazon would you be able to try with the change below?
<<<    return remap_pfn_range(vma, vaddr, pfn, size, __pgprot(__sme_clr(pgprot_val(prot))));
>>>    return remap_pfn_range(vma, vaddr, pfn, size, __pgprot(__sme_set(pgprot_val(prot))));

**Comment by wzamazon** [comment] 2022-12-10 02:14
>would you be able to try with the change below?

I tried the suggested change, but it did not fix the issue. will try to download the kernel source as suggested.

**Comment by pakmarkthub** [comment] 2022-12-12 01:07
Hi @wzamazon,
Can you try this patch? https://github.com/NVIDIA/gdrcopy/tree/dev-issue-240

**Comment by wzamazon** [comment] 2022-12-13 01:41
@pakmarkthub 

I tried the patch, but it did not solve the issue.

Is there anything you need me to print that can help you debug the issue?

**Comment by pakmarkthub** [comment] 2022-12-13 01:59
Hi @wzamazon,

I suspect that the write-combine (wc) mapping is the root cause. However, I don't have any proof. It would be good if you can enable the kernel debugging as Davide suggested.

I have updated https://github.com/NVIDIA/gdrcopy/tree/dev-issue-240 to completely disable wc mapping. There is a big performance hit, but it can be used to prove my assumption. Can you try that branch again?

**Comment by drossetti** [comment] 2022-12-15 01:03
```
<<<    return remap_pfn_range(vma, vaddr, pfn, size, __pgprot(__sme_clr(pgprot_val(prot))));
>>>    return remap_pfn_range(vma, vaddr, pfn, size, __pgprot(__sme_set(pgprot_val(prot))));
```
I think this happens because the cc_mask is different between Intel and AMD CC, so __sme_ macros cannot be used, unless in your kernel those have been upgraded to distinguish the two platforms.

**Comment by drossetti** [comment] 2023-01-05 21:35
@wzamazon coming back to this issue.

Please see my earlier questions:
> can you also check the implementation of io_remap_pfn_range in your kernel?
> Is 5.10.135-122.509 an internal version?
> Is its source available somewhere?

If it is easier, would you be able to just point us to the source code for your specific kernel?

**Comment by wzamazon** [comment] 2023-01-05 21:42
> can you also check the implementation of io_remap_pfn_range in your kernel?

I am not familiar with kernel development. Can you give me a pointer about which source file I should look at?


> Is 5.10.135-122.509 an internal version?

5.10.135-122.509  is the kernel used by amazon linux 2 (which I was using).

> If it is easier, would you be able to just point us to the source code for your specific kernel?

If you have access to an AWS EC2 instance that uses amazon linux 2, you can run `yumdownloader --source kernel` to get its kernel source.

I was able to download the kernel source this way. but it is quite big

**Comment by drossetti** [comment] 2023-10-20 02:17
v2.4 should have a fix for this issue.

**Closed by drossetti** 2023-10-20 02:17 UTC
Labels: bug
